-- Yogna Saathi Oracle DBMS Integration Script
-- Run in Oracle SQL Developer. This script demonstrates the real database
-- layer that the website would call through a Node.js/Express backend.

CREATE TABLE scheme_domain (
  domain_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  domain_name VARCHAR2(80) NOT NULL UNIQUE,
  ministry_name VARCHAR2(120),
  active_flag CHAR(1) DEFAULT 'Y' CHECK (active_flag IN ('Y', 'N'))
);

CREATE TABLE location (
  location_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_location_id NUMBER,
  location_name VARCHAR2(100) NOT NULL,
  location_type VARCHAR2(30) CHECK (location_type IN ('STATE', 'DISTRICT', 'BLOCK', 'VILLAGE')),
  CONSTRAINT fk_location_parent FOREIGN KEY (parent_location_id)
    REFERENCES location(location_id)
);

CREATE TABLE occupation (
  occupation_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  occupation_name VARCHAR2(80) NOT NULL UNIQUE
);

CREATE TABLE policy_scheme (
  scheme_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  domain_id NUMBER NOT NULL,
  scheme_name VARCHAR2(160) NOT NULL,
  benefit_type VARCHAR2(80),
  launch_year NUMBER(4),
  CONSTRAINT fk_scheme_domain FOREIGN KEY (domain_id)
    REFERENCES scheme_domain(domain_id)
);

CREATE TABLE scheme_benefit (
  benefit_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scheme_id NUMBER NOT NULL,
  benefit_amount NUMBER,
  benefit_frequency VARCHAR2(30),
  annual_value NUMBER,
  CONSTRAINT fk_benefit_scheme FOREIGN KEY (scheme_id)
    REFERENCES policy_scheme(scheme_id)
);

CREATE TABLE eligibility_criteria (
  criteria_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scheme_id NUMBER NOT NULL,
  min_age NUMBER DEFAULT 0,
  max_age NUMBER DEFAULT 120,
  gender VARCHAR2(10) DEFAULT 'ANY',
  marital_status VARCHAR2(30),
  max_income NUMBER,
  caste_category VARCHAR2(30),
  bpl_required CHAR(1) DEFAULT 'N' CHECK (bpl_required IN ('Y', 'N')),
  disability_required CHAR(1) DEFAULT 'N' CHECK (disability_required IN ('Y', 'N')),
  occupation_required VARCHAR2(80),
  CONSTRAINT fk_criteria_scheme FOREIGN KEY (scheme_id)
    REFERENCES policy_scheme(scheme_id)
);

CREATE TABLE beneficiary (
  beneficiary_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  location_id NUMBER NOT NULL,
  occupation_id NUMBER,
  full_name VARCHAR2(120) NOT NULL,
  age NUMBER CHECK (age BETWEEN 0 AND 120),
  gender VARCHAR2(10),
  marital_status VARCHAR2(30),
  annual_income NUMBER,
  caste_category VARCHAR2(30),
  bpl_flag CHAR(1) DEFAULT 'N' CHECK (bpl_flag IN ('Y', 'N')),
  disability_flag CHAR(1) DEFAULT 'N' CHECK (disability_flag IN ('Y', 'N')),
  CONSTRAINT fk_beneficiary_location FOREIGN KEY (location_id)
    REFERENCES location(location_id),
  CONSTRAINT fk_beneficiary_occupation FOREIGN KEY (occupation_id)
    REFERENCES occupation(occupation_id)
);

CREATE TABLE document (
  document_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  beneficiary_id NUMBER NOT NULL,
  document_type VARCHAR2(80) NOT NULL,
  verified_flag CHAR(1) DEFAULT 'N' CHECK (verified_flag IN ('Y', 'N')),
  CONSTRAINT fk_document_beneficiary FOREIGN KEY (beneficiary_id)
    REFERENCES beneficiary(beneficiary_id)
);

CREATE TABLE eligibility_match (
  beneficiary_id NUMBER NOT NULL,
  scheme_id NUMBER NOT NULL,
  match_score NUMBER(5,2),
  calculated_on DATE DEFAULT SYSDATE,
  PRIMARY KEY (beneficiary_id, scheme_id),
  CONSTRAINT fk_match_beneficiary FOREIGN KEY (beneficiary_id)
    REFERENCES beneficiary(beneficiary_id),
  CONSTRAINT fk_match_scheme FOREIGN KEY (scheme_id)
    REFERENCES policy_scheme(scheme_id)
);

CREATE TABLE beneficiary_enrollment (
  enrollment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  beneficiary_id NUMBER NOT NULL,
  scheme_id NUMBER NOT NULL,
  enrollment_status VARCHAR2(30) DEFAULT 'PENDING',
  applied_on DATE DEFAULT SYSDATE,
  CONSTRAINT fk_enrollment_beneficiary FOREIGN KEY (beneficiary_id)
    REFERENCES beneficiary(beneficiary_id),
  CONSTRAINT fk_enrollment_scheme FOREIGN KEY (scheme_id)
    REFERENCES policy_scheme(scheme_id)
);

CREATE TABLE awareness_campaign (
  campaign_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  location_id NUMBER NOT NULL,
  campaign_name VARCHAR2(140) NOT NULL,
  ngo_name VARCHAR2(120),
  campaign_cost NUMBER,
  start_date DATE,
  CONSTRAINT fk_campaign_location FOREIGN KEY (location_id)
    REFERENCES location(location_id)
);

CREATE TABLE campaign_impact (
  impact_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_id NUMBER NOT NULL,
  awareness_before NUMBER(5,2),
  awareness_after NUMBER(5,2),
  new_enrollments NUMBER,
  CONSTRAINT fk_impact_campaign FOREIGN KEY (campaign_id)
    REFERENCES awareness_campaign(campaign_id)
);

INSERT INTO scheme_domain (domain_name, ministry_name) VALUES ('Social Security', 'Ministry of Social Justice');
INSERT INTO scheme_domain (domain_name, ministry_name) VALUES ('Healthcare', 'Ministry of Health');
INSERT INTO scheme_domain (domain_name, ministry_name) VALUES ('Education', 'Ministry of Education');
INSERT INTO scheme_domain (domain_name, ministry_name) VALUES ('Women & Child', 'Ministry of Women and Child Development');

INSERT INTO location (location_name, location_type) VALUES ('Punjab', 'STATE');
INSERT INTO location (parent_location_id, location_name, location_type) VALUES (1, 'Ludhiana', 'DISTRICT');
INSERT INTO location (parent_location_id, location_name, location_type) VALUES (2, 'Khera', 'VILLAGE');
INSERT INTO location (parent_location_id, location_name, location_type) VALUES (2, 'Raikot', 'VILLAGE');

INSERT INTO occupation (occupation_name) VALUES ('Homemaker');
INSERT INTO occupation (occupation_name) VALUES ('Student');
INSERT INTO occupation (occupation_name) VALUES ('Farmer');

INSERT INTO policy_scheme (domain_id, scheme_name, benefit_type, launch_year)
VALUES (1, 'Indira Gandhi National Widow Pension', 'Cash pension', 1995);
INSERT INTO scheme_benefit (scheme_id, benefit_amount, benefit_frequency, annual_value)
VALUES (1, 1500, 'MONTHLY', 18000);
INSERT INTO eligibility_criteria
  (scheme_id, min_age, max_age, gender, marital_status, max_income)
VALUES
  (1, 40, 120, 'F', 'Widow', 100000);

INSERT INTO policy_scheme (domain_id, scheme_name, benefit_type, launch_year)
VALUES (1, 'Old Age Pension Scheme', 'Cash pension', 2007);
INSERT INTO scheme_benefit (scheme_id, benefit_amount, benefit_frequency, annual_value)
VALUES (2, 1000, 'MONTHLY', 12000);
INSERT INTO eligibility_criteria
  (scheme_id, min_age, max_age, gender, max_income)
VALUES
  (2, 60, 120, 'ANY', 120000);

INSERT INTO policy_scheme (domain_id, scheme_name, benefit_type, launch_year)
VALUES (2, 'Ayushman Bharat PM-JAY', 'Health insurance', 2018);
INSERT INTO scheme_benefit (scheme_id, benefit_amount, benefit_frequency, annual_value)
VALUES (3, 500000, 'YEARLY', 500000);
INSERT INTO eligibility_criteria
  (scheme_id, min_age, max_age, gender, max_income, bpl_required)
VALUES
  (3, 0, 120, 'ANY', 150000, 'Y');

INSERT INTO beneficiary
  (location_id, occupation_id, full_name, age, gender, marital_status, annual_income, caste_category, bpl_flag)
VALUES
  (3, 1, 'Gurmeet Kaur', 65, 'F', 'Widow', 36000, 'General', 'Y');

INSERT INTO document (beneficiary_id, document_type, verified_flag) VALUES (1, 'Aadhaar', 'Y');
INSERT INTO document (beneficiary_id, document_type, verified_flag) VALUES (1, 'Ration Card', 'Y');
INSERT INTO document (beneficiary_id, document_type, verified_flag) VALUES (1, 'Widow Certificate', 'Y');

CREATE OR REPLACE PROCEDURE calculate_beneficiary_eligibility (
  p_beneficiary_id IN NUMBER
) AS
BEGIN
  DELETE FROM eligibility_match
  WHERE beneficiary_id = p_beneficiary_id;

  INSERT INTO eligibility_match (beneficiary_id, scheme_id, match_score)
  SELECT b.beneficiary_id,
         ec.scheme_id,
         100 AS match_score
  FROM beneficiary b
  JOIN eligibility_criteria ec
    ON b.age BETWEEN ec.min_age AND ec.max_age
   AND (ec.gender = 'ANY' OR ec.gender = b.gender)
   AND (ec.marital_status IS NULL OR ec.marital_status = b.marital_status)
   AND (ec.max_income IS NULL OR b.annual_income <= ec.max_income)
   AND (ec.caste_category IS NULL OR ec.caste_category = b.caste_category)
   AND (ec.bpl_required = 'N' OR b.bpl_flag = 'Y')
   AND (ec.disability_required = 'N' OR b.disability_flag = 'Y')
  WHERE b.beneficiary_id = p_beneficiary_id;

  COMMIT;
END;
/

BEGIN
  calculate_beneficiary_eligibility(1);
END;
/

-- Citizen result shown on the website.
SELECT b.full_name,
       ps.scheme_name,
       sd.domain_name,
       sb.annual_value,
       em.match_score
FROM eligibility_match em
JOIN beneficiary b ON b.beneficiary_id = em.beneficiary_id
JOIN policy_scheme ps ON ps.scheme_id = em.scheme_id
JOIN scheme_domain sd ON sd.domain_id = ps.domain_id
JOIN scheme_benefit sb ON sb.scheme_id = ps.scheme_id
WHERE b.beneficiary_id = 1;

-- Government/Admin dashboard query shown in the website.
SELECT l.location_name,
       COUNT(em.scheme_id) AS eligible_not_enrolled,
       SUM(sb.annual_value) AS missed_benefit
FROM location l
JOIN beneficiary b ON b.location_id = l.location_id
JOIN eligibility_match em ON em.beneficiary_id = b.beneficiary_id
JOIN scheme_benefit sb ON sb.scheme_id = em.scheme_id
LEFT JOIN beneficiary_enrollment be
  ON be.beneficiary_id = b.beneficiary_id
 AND be.scheme_id = em.scheme_id
WHERE be.enrollment_id IS NULL
GROUP BY l.location_name
ORDER BY missed_benefit DESC;

